version: '3'

services:
  acme-explorer-ui:
    build: ../
    environment: 
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${PORT}
    restart: on-failure
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
networks: 
  default:
    external:
      name: service-tier